-- =========================================================================
-- SUPABASE SCHEMA — WEB DOSSIER TERRENOS QUINTÃS
-- Projeto: zxwkviggbftqiqwnigjn
-- Execute este script no SQL Editor do seu Supabase Dashboard:
-- https://supabase.com/dashboard/project/zxwkviggbftqiqwnigjn/sql/new
--
-- Ordem das colunas (por importância):
--   id | nome | telemovel | quando_ligar | quando_visitar | mensagem | origem | status | created_at
--
-- O script é seguro para correr mais do que uma vez e PRESERVA as leads
-- já existentes (migra-as da tabela antiga para a nova estrutura).
-- =========================================================================

BEGIN;

-- 1. Nova tabela com as colunas na ordem certa
CREATE TABLE IF NOT EXISTS public.leads_v2 (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            TEXT        NOT NULL,
    telemovel       TEXT        NOT NULL,
    quando_ligar    TEXT,                      -- Melhor hora para contactar
    quando_visitar  TEXT,                      -- Preferência de dia para a visita
    mensagem        TEXT,
    origem          TEXT        DEFAULT 'Dossier Terreno Quintãs, Aveiro',
    status          TEXT        DEFAULT 'nova',
    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 2. Migrar leads antigas (se a tabela antiga existir e ainda não tiver sido migrada)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'leads'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'quando_ligar'
        ) THEN
            -- Extrai "Preferência de Visita" e "Melhor Hora" que antes iam dentro da mensagem
            INSERT INTO public.leads_v2 (nome, telemovel, quando_ligar, quando_visitar, mensagem, origem, status, created_at)
            SELECT
                nome,
                telemovel,
                NULLIF(trim(substring(mensagem FROM 'Melhor Hora para Contactar: ([^|]+)')), ''),
                NULLIF(trim(substring(mensagem FROM 'Preferência de Visita: ([^|]+)')), ''),
                mensagem,
                origem,
                status,
                created_at
            FROM public.leads
            ORDER BY created_at ASC;

            DROP TABLE public.leads CASCADE;
        ELSE
            -- Já está na estrutura nova: nada a migrar
            DROP TABLE public.leads_v2;
        END IF;
    END IF;
END $$;

-- 3. Renomear para o nome final
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'leads_v2'
    ) THEN
        ALTER TABLE public.leads_v2 RENAME TO leads;
        ALTER SEQUENCE IF EXISTS public.leads_v2_id_seq RENAME TO leads_id_seq;
    END IF;
END $$;

-- 4. Row Level Security (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir inserção anónima de leads" ON public.leads;
CREATE POLICY "Permitir inserção anónima de leads"
ON public.leads
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir leitura apenas a administradores" ON public.leads;
CREATE POLICY "Permitir leitura apenas a administradores"
ON public.leads
FOR SELECT
TO authenticated, service_role
USING (true);

-- Permissões necessárias para o formulário público inserir (incl. sequência do id)
GRANT INSERT ON public.leads TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 5. Índices de performance
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status     ON public.leads(status);

-- 6. Garantia: se a lead chegar com as respostas dentro da mensagem (versão antiga do site),
--    o próprio Supabase copia-as para as colunas certas:
--      "Melhor Hora para Contactar: …" → quando_ligar
--      "Preferência de Visita: …"      → quando_visitar
CREATE OR REPLACE FUNCTION public.leads_preencher_preferencias()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.mensagem IS NOT NULL THEN
        IF NEW.quando_ligar IS NULL OR trim(NEW.quando_ligar) = '' THEN
            NEW.quando_ligar := NULLIF(trim(COALESCE(
                substring(NEW.mensagem FROM 'Melhor Hora para Contactar: ([^|]+)'),
                substring(NEW.mensagem FROM 'Quando ligar: ([^|]+)')
            )), '');
        END IF;
        IF NEW.quando_visitar IS NULL OR trim(NEW.quando_visitar) = '' THEN
            NEW.quando_visitar := NULLIF(trim(COALESCE(
                substring(NEW.mensagem FROM 'Preferência de Visita: ([^|]+)'),
                substring(NEW.mensagem FROM 'Quando visitar: ([^|]+)')
            )), '');
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_leads_preencher_preferencias ON public.leads;
CREATE TRIGGER trg_leads_preencher_preferencias
BEFORE INSERT OR UPDATE ON public.leads
FOR EACH ROW EXECUTE FUNCTION public.leads_preencher_preferencias();

-- Corrigir as leads que já entraram com as colunas vazias
UPDATE public.leads
SET mensagem = mensagem
WHERE (quando_ligar IS NULL OR quando_visitar IS NULL)
  AND (mensagem ILIKE '%Melhor Hora para Contactar:%'
       OR mensagem ILIKE '%Preferência de Visita:%'
       OR mensagem ILIKE '%Quando ligar:%'
       OR mensagem ILIKE '%Quando visitar:%');

COMMIT;

-- 7. Atualizar a cache da API do Supabase para reconhecer as novas colunas
NOTIFY pgrst, 'reload schema';
